apiVersion: v1
kind: servive
metadata: 
   name: mynginx-svs
   labels:  
      app: mynginx
spec:
  type: nodeport
  ports:
  - port: 80
    nodeport: 30001
    protocol: TCP
  selector:
      app: mynginx